apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app
spec:
  replicas: 3  # <--- The Magic Number
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
      - name: finance-container
        image: praveenkumarilla459/internal-finance-system:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  type: NodePort
  selector:
    app: finance
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005 # We force a specific port this time!